import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className="antialiased bg-gray-100">
        <Provider>
        {children}
        </Provider>       
       
       
      </body>
    </html>
  );
}
